### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by rlbaas** [CodeRed2771/2016ScoutingApp#1]

**Comment by mspoehr** [comment]
Hey,  you created an issue! :)

**Comment by carter-et** [comment]
what on earth

On Tue, Mar 1, 2016 at 4:14 PM, Michael Spoehr notifications@github.com
wrote:

> Hey, you created an issue! :)
> 
> On Tue, Mar 1, 2016, 4:13 PM rlbaas notifications@github.com wrote:
> 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CodeRed2771/2016ScoutingApp/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CodeRed2771/2016ScoutingApp/issues/1#issuecomment-190908276
> .

## 

Ethan L Carter
